version: "3.1"

services:
    web:
        image: nginx:alpine
        volumes:
            - ./app/public:/app/public
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 2222:80

    app:
        build:
            context: ./app
            dockerfile: ../php/Dockerfile
            args:
                USER_ID: 1000
                GROUP_ID: 1000
        volumes:
            - ./app:/app
            - ./php/php.ini:/usr/local/etc/php/php.ini
    
    db:
        image: mysql:5
        restart: always
        volumes:
            - db_volume:/var/lib/mysql
        ports:
            - 2223:3306
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=ekar
            - MYSQL_USER=ekar
            - MYSQL_PASSWORD=ekar
    
    db_test:
        image: mysql:5
        restart: always
        volumes:
            - db_test_volume:/var/lib/mysql
        ports:
            - 2225:3306
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=ekar_test
            - MYSQL_USER=ekar
            - MYSQL_PASSWORD=ekar
    
    adminer:
        image: adminer
        restart: always
        ports:
            - 2224:8080

volumes:
    db_volume:
    db_test_volume:
